name: mdBook Deploy
on:
  push:
    branches: [ main ]    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache mdbook-classy
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.cargo/bin/mdbook-classy
          key: ${{ runner.os }}

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
          
      - name: Install mdbook-linkcheck
        run: |
          mkdir -p mdbook-linkcheck && cd "$_" && \
          curl -L https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/latest/download/mdbook-linkcheck.x86_64-unknown-linux-gnu.zip -o mdbook-linkcheck.zip && \
          unzip "$_" && \
          chmod +x mdbook-linkcheck && \
          cp mdbook-linkcheck ~/.cargo/bin/
          
      - name: Install mdbook-classy
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install mdbook-classy

      - name: Build mdBook
        run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
